### ISSUE TITLE
debug_email not in defaults, can't be used via cfg

### ISSUE THREAD

**Issue by zenspider** [lestercheung/p4review#2]
the perforce repo you host this on is erroring 500 right now (hah)... so I'm filing this here. 

I was trying to debug email and couldn't. It kept giving me errors about needing to regenerate config. Eventually I realized it needed to have a default value set for the config parser to allow it to be in the config file.

**Comment by lestercheung** [comment]
Hello from 2021! I am no longer working for Perforce and have since lost access to the Perforce Workshop as well! Let's be honest Perforce is great for in-house projects but for random scripts like this git is the way to go ^_^

I will have a look at this and the other issues that you have filed. Stay safe wherever you are internet stranger.

**Comment by lestercheung** [comment]
Ah I see what you mean now. The `-P` or `--debug-email` option is for command-line only. I usually do something similar while testing:

```
[[ -f p4review2.pid ]] && rm p4review2.py
python3 p4review2.py <options> -P 2>&1 |less
```
